# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
trigger:
- main

pool:
  vmImage: 'ubuntu-16.04' # other options: 'macOS-10.14', 'vs2017-win2016'
#pool:
#  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    codeCoverageToolOption: 'JaCoCo'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx3072m'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'
    checkStyleRunAnalysis: true
    pmdRunAnalysis: true
    findBugsRunAnalysis: true

# Publish code coverage results
# Publish Cobertura or JaCoCo code coverage results from a build
#- task: PublishCodeCoverageResults@1
#  inputs:
#    #codeCoverageTool: 'JaCoCo' # Options: cobertura, jaCoCo
#    summaryFileLocation: 
#    #pathToSources: # Optional
#    #reportDirectory: # Optional
#    #additionalCodeCoverageFiles: # Optional
#    #failIfCoverageEmpty: false # Optional